# Site settings
url: https://olympusrealtypm.github.io
baseurl: /html5up-arcana
title: Arcana
subtitle: by HTML5 UP
description: A FREE AND FULLY RESPONSIVE SITE TEMPLATE

# Contact
email: info@olympusrealtypm.ca
street_address: 1234 Somewhere Road
city: Ajax
state: Ontario
zip_code: L1S-3L8
country: Canada
phone: (416) 856-7405

# Social settings
500px_url:
facebook_url: https://www.facebook.com/olympusrealtypm
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: https://www.instagram.com/olympusrealtypm/?hl=en
linkedin_url: https://www.linkedin.com/company/olympus-realty-pm/
pinterest_url:
slack_url:
twitter_url: 
