# Site settings
title: Arcana
email: info@olympusrealtypm.ca
description: A fully responsive site template designed by <a href="https://html5up.net">HTML5 UP</a> and released<br />for free under the <a href="https://html5up.net/license">Creative Commons</a> license.
baseurl: "/olympusrealty" # the subpath of your site, e.g. /blog
url: "https://html5up.net/arcana" # the base hostname & protocol for your site

# Contact
email: info@olympusrealtypm.ca
street_address: 1234 Somewhere Road
city: Ajax
state: Ontario
zip_code: L1S-3L8
country: Canada
phone: (416) 856-7405

# Social settings
facebook_url: https://www.facebook.com/olympusrealtypm
instagram_url: https://www.instagram.com/olympusrealtypm/?hl=en
linkedin_url: https://www.linkedin.com/company/olympus-realty-pm/
